# Project information
site_name: Cyber Security Incident Response
site_description: Cyber Security Incident Response Team Site
site_author: CIR Team

# Repository
repo_url: https://github.com/samkshah/ActionsTest
edit_uri: edit/main/docs/
docs_dir: docs/

# Theme Configuration
theme:
  name: material  
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  custom_dir: custom_theme/
  site_dir: site/
  prev_next_button_location: both
  
# Customization
extra_css:
  - css/extra.css
markdown_extensions:
    - admonition
    - attr_list
    - meta
    - abbr
    - pymdownx.snippets
    - pymdownx.details
    - pymdownx.highlight:
        anchor_linenums: true
        auto_title: true
        linenums: true
        linenums_style: pymdownx-inline
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    
# Page tree
nav:
  - Home: 'index.md'
  - Products:
    - Security Analytics:
        - Overview: SecAnalytics/overview.md
        - Logging Standards: SecAnalytics/logging-standards.md
        - Log Types: SecAnalytics/log-types.md
        - Processes and Procedures: SecAnalytics/processes.md
        - Log Integration Patterns: SecAnalytics/log-integration-patterns.md
        - Log Examples: SecAnalytics/log-examples.md
        - Log Analysis: SecAnalytics/log-analysis.md
    - EPP/EDR: EDR-EPP/about.md
    - Email Security: EmailSecurity/about.md
    - SOAR: SOAR/about.md
    - Adversary Emulation: AET/about.md
  - References: 
    - FAQs: 'References/faq.md'
    - Detection Prioritization: References/detection-prioritization.md
  - About CIR: 'about-cir.md'
