# This action is used to build and deploy site using mkdocs
name: Build and Deploy Site
on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy to gh-pages
        run: |
          mkdocs gh-deploy --force

  print-context:
      runs-on: ubuntu-latest
      steps:
        - name: Show event context
          env: 
            EVENT_CONTEXT: ${{ toJSON(github.event)}}
          run: echo "$EVENT_CONTEXT"

        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJSON(github) }}
          run: echo "$GITHUB_CONTEXT"
