# Create github workflow file to get issue data

name: Create Incident

on:
  issue_comment:
    types: [created,edited]
  issues:
    types: [opened,edited]

jobs:

  createIncident-NonProd:
    # if: github.event.issue.type == 'opened'
    runs-on: ubuntu-latest
    env:
      issueNumber: ${{github.event.issue.number}}
      issueTitle: ${{github.event.issue.title}}
      issueBody: ${{github.event.issue.body}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: echo Details
        run: |
          echo $issueNumber
          echo $issueTitle
          echo $issueBody

      - name: Extract username
        id: extract_username
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const regex-username = /username[^\d]+(\d+)/;
            const body = github.context.payload.issue.body;
            const matchUserName = body.match (regex-username);
            if (matchUserName) {
              console.log(`::set-output name=issueUserName::${matchUserName[1]}`);
            }
      - name: Use extracted username
        run: |
          echo "Username: ${{ steps.extract_username.outputs.issueUserName }}"

  # createIncident-Prod:
  #   if: github.event.comment.body == '/createIncident-prod'
  #   runs-on: ubuntu-latest
  #   env:
  #     issueNumber: ${{github.event.issue.number}}
  #     issueTitle: ${{github.event.issue.title}}
  #     issueBody: ${{github.event.issue.body}}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: echo Details
  #       run: |
  #         echo $issueNumber
  #         echo $issueTitle
  #         echo $issueBody

