# Create github workflow file to get issue data

name: Create Incident

on:
  issue_comment:
    types: [created,edited]
  issues:
    types: [opened,edited]
  workflow_dispatch:
    

jobs:
  createIncident-NonProd:
    # if: github.event.issue.type == 'opened'
    runs-on: ubuntu-latest
    env:
      issueNumber: ${{github.event.issue.number}}
      issueTitle: ${{github.event.issue.title}}
      issueBody: ${{github.event.issue.body}}
    steps:
      - name: Extract part from issue body
        id: extract_username
        if: ${{github.event.issue.body}} contains 'username' && ${{github.event.issue.body}} contains '\d{6}'
        run: |
          echo $issueBody
          echo "...."
          # join multiple lines into one
          issueBody=$(echo $issueBody | tr -d '\n' | tr -d '\r')
          echo $issueBody
        # echo "issueUserName=${{github.event.issue.body}} | grep -oP '(?<=username: )\d+'" >> $GITHUB_OUTPUT
      #     echo "issueUserName=$issueUserName" >> $GITHUB_OUTPUT

      # - name: Echo issueUserName
      #   run: |
      #     echo "UserName is: ${{steps.extract_username.outputs.issueUserName}}"