name: Issues triage
on:
  issues:
    types:
      - "opened"
      - "labeled"

jobs:
  issue-created:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: label-triage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit $ISSUE_URL --add-label "triage"
  label-added:
    if: github.event.action == 'labeled'
    runs-on: ubuntu-latest
    steps:
      - name: Label Added
        env:
          LABEL_NAME: ${{ github.event.label.name }}
        run: echo "$LABEL_NAME issue added"

  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show event context
        env: 
          EVENT_CONTEXT: ${{ toJSON(github.event)}}
        run: echo "$EVENT_CONTEXT"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"