# Create github workflow file to get issue data

name: Get Issue Data

on:
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled]

jobs:
  getIssueDetails:
    runs-on: ubuntu-latest
    env:
      issueNumber = ${{github.event.issue.number}}
      issueTitle = ${{github.event.issue.title}}
      issueBody = ${{github.event.issue.body}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: echo Details
        run: |
          echo $issueNumber
          echo $issueTitle
          echo $issueBody