# This workflow is used to auto-label new issues and also comments on existing labels based

name: Issues triage
on:
  issues:
    types: ["opened", "labeled"]

jobs:
  issue-created:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: New Issue Label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit $ISSUE_URL --add-label "triage"

  label-added:
    if: github.event.action == 'labeled'
    runs-on: ubuntu-latest
    permissions: 
      issues: write
    env:
      LABEL_NAME: ${{ github.event.label.name }}
    steps:
      - name: help wanted
        if: ${{ env.LABEL_NAME == 'help wanted' }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ":wave: Hello CIR team!\n\n:heavy_exclamation_mark: We need your help with this issue. If you are interested to collaborate, please follow these steps...\n- Assign this issue to yourself using 'Assignees' field on the right\n- Add comments to this issue whenever you need inputs from others\n- Make sure to reference this issue in your pull request. :sparkles:\n\n:bow: Thank you for your time! :sparkles:"
            })

      - name: help wanted2
        if: ${{ env.LABEL_NAME == 'help wanted' }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `:wave: Hello CIR team!
                :heavy_exclamation_mark: We need your help with this issue. If you are interested to collaborate, please follow these steps...
                  - Assign this issue to yourself using 'Assignees' field on the right
                  - Add comments to this issue whenever you need inputs from others
                  - Make sure to reference this issue in your pull request. :sparkles:                
                  
                  :bow: Thank you for your time! :sparkles:`
            })

  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show event context
        env: 
          EVENT_CONTEXT: ${{ toJSON(github.event)}}
        run: echo "$EVENT_CONTEXT"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"