# This workflow is used to triage new or re-opened issues
name: New Issue
on:
  issues:
    types: ["opened","reopened"]

jobs:
  issue-triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: triage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit $ISSUE_URL --add-label "triage"