# Create github workflow file to get issue data

name: Create Incident

on:
  issue_comment:
    types: [created,edited]
  issues:
    types: [opened,edited]
  workflow_dispatch:
    

jobs:
  createIncident-NonProd:
    # if: github.event.issue.type == 'opened'
    runs-on: ubuntu-latest
    env:
      issueNumber: ${{github.event.issue.number}}
      issueTitle: ${{github.event.issue.title}}
      issueBody: ${{github.event.issue.body}}
    steps:
      - name: Extract part from issue body
        id: extract_username
        if: ${{github.event.issue.body}} contains 'username' && ${{github.event.issue.body}} contains '\d{6}'
        run: |
          echo "${{github.event.issue.body}}" | sed ':a; N; $!ba; s/\n/ /g' | grep -oP '(?<!username)\d+'