# Create github workflow file to get issue data

name: Get Issue Data

on:
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled]

jobs:
  getIssueDetails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo Details
        run: |
          echo "Issue Number: ${{env.ISSUE_NUMBER}}"
          echo "Issue Title: ${{env.ISSUE_TITLE}}"
          echo "Issue Body: ${{env.ISSUE_BODY}}"