name: Issues triage
on:
  issues:
    types:
      - opened

jobs:
  issue-created:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: label-triage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit $ISSUE_URL --add-label "triage"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
    

