# This workflow is used to triage new or re-opened issues
name: New Issue
on:
  issues:
    types: ["opened","reopened"]

jobs:
  issue-triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: triage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit $ISSUE_URL --add-label "triage"
      - name: comments
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ":wave: This issue is tagged with 'triage' label. It'll be removed automatically when someone is assigned to work on."
            })