name: Issues triage
on:
  issues:
    types:
      - "opened"
      - "labeled"

jobs:
  issue-created:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: new issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit $ISSUE_URL --add-label "triage"

      - name: new issue2
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })

  label-added:
    if: github.event.action == 'labeled'
    runs-on: ubuntu-latest
    permissions: 
      issues: write
    env:
      LABEL_NAME: ${{ github.event.label.name }}
    steps:
      - name: documentation
        if: ${{ env.LABEL_NAME == 'documentation' }}
        run: echo "Build and deploy site in this step..."

      - name: help wanted
        if: ${{ env.LABEL_NAME == 'help wanted' }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            :heavy_exclamation_mark: We need your help with this issue. If you are interested to collaborate, please follow these steps...
            - Assign this issue to yourself using 'Assignees' field on the right
            - Add comments to this issue whenever you need inputs from others
            - Make sure to reference this issue in your pull request. :sparkles: 
            
            :bow: Thank you for your time! :sparkles:
            
      - name: help wanted2
        if: ${{ env.LABEL_NAME == 'help wanted' }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number
              owner: context.repo.owner
              repo: context.repo.repo
              body: |
                ':heavy_exclamation_mark: We need your help with this issue. If you are interested to collaborate, please follow these steps...
                  - Assign this issue to yourself using 'Assignees' field on the right
                  - Add comments to this issue whenever you need inputs from others
                  - Make sure to reference this issue in your pull request. :sparkles:
                  
                  :bow: Thank you for your time! :sparkles:'
            })

  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show event context
        env: 
          EVENT_CONTEXT: ${{ toJSON(github.event)}}
        run: echo "$EVENT_CONTEXT"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"