# Create github workflow file to get issue data

name: Get Issue Data

on:
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled]

jobs:
  getIssueDetails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Get Issue Details
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = context.payload.issue
            const issueNumber = issue.number
            const issueTitle = issue.title
            const issueBody = issue.body
            const issueState = issue.state
            const issueLabels = issue.labels
            const issueAssignees = issue.assignees
            const issueMilestone = issue.milestone
            const issueCreatedAt = issue.created_at
            const issueUpdatedAt = issue.updated_at
            const issueClosedAt = issue.closed_at
            const issueAuthor = issue.user.login
            const issueAuthorAssociation = issue.author_association
            const issueComments = issue.comments
            const issueReactions = issue.reactions
            const issueLocked = issue.locked
            const issueActiveLockReason = issue.active_lock_reason
            const issuePullRequest = issue.pull_request
            const issueLinks = issue.html_url
            const issueNodeID = issue.node_id
            const issueURL = issue.url
            const issueEventsURL = issue.events_url
            const issueCommentsURL = issue.comments_url
            const issueReactionsURL = issue.reactions_url
            const issueLabelsURL = issue.labels_url
            const issueAssigneesURL = issue.assignees_url
            const issueTimelineURL = issue.timeline_url
            const issueLockedURL = issue.lock_url
            const issueAssignee = issue.assignee
            const issueAssigneeLogin = issue.assignee.login
            const issueAssigneeID = issue.assignee.id
            const issueAssigneeNodeID = issue.assignee.node_id
            const issueAssigneeAvatarURL = issue.assignee.avatar_url
            const issueAssigneeGravatarID = issue.assignee.gravatar_id
            const issueAssigneeURL = issue.assignee.url
            const issueAssigneeHTMLURL = issue.assignee.html_url
            const issueAssigneeFollowersURL = issue.assignee.followers_url
            const issueAssigneeFollowingURL = issue.assignee.following_url
            const issueAssigneeGistsURL = issue.assignee.gists_url
            const issueAssigneeStarredURL = issue.assignee.starred_url
            const issueAssigneeSubscriptionsURL = issue.assignee.subscriptions_url
            const issue
      - name: Create Issue Data File
        uses: peter-evans/create-or-update-file@v1
        with:
          path: issue-data/${{ github.event.issue.number }}.json
          message: Create Issue Data File
          content: |
            {
              "issueNumber": "${{ github.event.issue.number }}",
              "issueTitle": "${{ github.event.issue.title }}",
              "issueBody": "${{ github.event.issue.body }}",
              "issueState": "${{ github.event.issue.state }}",
              "issueLabels": "${{ github.event.issue.labels }}",
              "issueAssignees": "${{ github.event.issue.assignees }}",
              "issueMilestone": "${{ github.event.issue.milestone }}",
              "issueCreatedAt": "${{ github.event.issue.created_at }}",
              "issueUpdatedAt": "${{ github.event.issue.updated_at }}",
              "issueClosedAt": "${{ github.event.issue.closed_at }}",
              "issueAuthor": "${{ github.event.issue.user.login }}",
              "issueAuthorAssociation": "${{ github.event.issue.author_association }}",
              "issueComments": "${{ github.event.issue.comments }}",
              "issueReactions": "${{ github.event.issue.reactions }}",
              "issueLocked": "${{ github.event.issue.locked }}",
              "issueActiveLockReason": "${{ github.event.issue.active_lock_reason }}",
              "issuePullRequest": "${{ github.event.issue.pull_request }}",
              "issueLinks": "${{ github.event.issue.html_url }}",
              "issueNodeID": "${{ github.event.issue.node_id }}",
              "issueURL": "${{ github.event.issue.url }}",
              "issueEventsURL": "${{ github.event.issue.events_url }}",
              "issueCommentsURL": "${{ github.event.issue.comments_url }}",
              "issueReactionsURL": "${{ github.event.issue.reactions_url }}",
              "issueLabelsURL": "${{ github.event.issue.labels_url }}",
              "issueAssigneesURL": "${{ github.event.issue.assignees_url }}",
              "issueTimelineURL": "${{ github.event.issue.timeline_url }}",
              "issueLockedURL": "${{ github.event.issue.lock_url }}",
              "issueAssignee": "${{ github.event.issue.assignee }}",
              "issueAssigneeLogin": "${{ github.event.issue.assignee.login }}",
              "issueAssigneeID": "${{ github.event.issue.assignee.id }}",
              "issueAssignee