# Create github workflow file to get issue data

name: Get Issue Data

on:
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled]

jobs:
  getIssueDetails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo Details
        run: |
          const issueNumber = ${{github.event.issue.number}}"
          echo issueTitle = ${{github.event.issue.title}}"
          echo issueBody = ${{github.event.issue.body}}"

      - name: echo Details
        run: |
          echo $issueNumber
          echo $issueTitle
          echo $issueBody