name: "Close stale issues"
on:
  schedule:
  - cron: "* * * * *"

jobs:
  stale:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 45 days with no activity. A non-Author needs to comment or this will be closed in 5 days'
        exempt-issue-labels: 'development, bug'
        days-before-issue-stale: 0
        days-before-issue-close: 5
        remove-stale-when-updated: true